exclude_patterns:
 - "**/_test_/"
 - "src/index.js"
 - "**/_coverage_/"
 - "**/node_modules/"
 - "**/_coverage_/"
checks:
  method-lines:
    config:
      threshold: 80
  similar-code:
    enabled: false
  identical-code:
    enabled: true
    