module.exports = {
  bail: false,
  clearMocks: true,
  collectCoverage: false,
  collectCoverageFrom: [
    'src/**/*.{js,jsx}',
    '!src/index.js',
    '!src/store/index.js',
    '!src/reducers/index.js',
    '!src/actions/types.js',
    '!src/utils/decoded.js',
    '!**/node_modules/**',
    '!**/vendor/**',
  ],
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: [
    '/node_modules/',
  ],
  coverageReporters: [
    'json',
    'text',
    'lcov',
    'clover',
  ],
  coverageThreshold: {
    global: {
      branches: 85,
      functions: 85,
      lines: 85,
    },
  },
  errorOnDeprecated: true,
  moduleFileExtensions: ['js', 'json', 'jsx'],
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/_test_/__mocks__/fileMock.js',
    '\\.(css|scss)$': '<rootDir>/_test_/__mocks__/styleMock.js',
  },
  setupFilesAfterEnv: ['./tests.setup.js', '<rootDir>/_test_/__mocks__/localMock.js'],
  setupFiles: ['<rootDir>/_test_/__mocks__/localMock.js'],
  // setupTestFrameworkScriptFile: ['<rootDir>/_test_/__mocks__/localMock.js'],
  testEnvironment: 'jsdom',
  testMatch: ['**/__tests__/**/*.js?(x)', '**/?(*.)+(spec|test).js?(x)'],
  testPathIgnorePatterns: ['/node_modules/'],
  testURL: 'http://localhost',
  transform: {
    '^.+\\.jsx?$': 'babel-jest',
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/(?!(react-spring)/)'],
  verbose: true,
};
