export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const NEW_ARTICLE = 'NEW_ARTICLE';
export const TEST_DISPATCH = 'TEST_DISPATCH';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const SET_LOADING = 'SET_LOADING';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_ARTICLES = 'SET_CURRENT_ARTICLES';
