export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const NEW_ARTICLE = 'NEW_ARTICLE';
export const RESET_PASSWORD_EMAIL = 'RESET_PASSWORD';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const RESET_PASSWORD_EMAIL_FAILURE = 'RESET_PASSWORD_FAILURE';
export const SET_NEW_PASSWORD_FAILURE = 'SET_NEW_PASSWORD_FAILURE';
