export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const NEW_ARTICLE = 'NEW_ARTICLE';

export const CREATE_ARTICLE_START = 'CREATE_ARTICLE_START';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';
