
export const successProfileResponse = {
  status: 200,
  message: 'Operation successful',
  data: [
    {
      firstName: 'Henry',
      lastName: 'Okonkwo',
      userName: 'choko',
      email: 'henry.okonkwo@andela.com',
      bio: 'Software developer',
      imageUrl: 'http://image.com',
    },
  ],
};

export const errorProfileResponse = {
  status: 404,
  message: 'Article not found',
};

export const successArticleResponse = {
  status: 200,
  message: 'All articles fetched successfully',
  data: [
    {
      articles: [
        {
          id: 124,
          title: 'Lifestyle',
          slug: 'lifestyle-8f155e88',
          description: 'superyacht',
          body: 'In this report, the global Sunflower Oil Meal market is valued at USD XX million in 2019',
          imageUrl: 'http://image.png',
          isDraft: false,
          views: 0,
          read: 0,
          readRatio: 0,
          userId: 72,
          catId: 2,
        },
        {
          id: 125,
          title: 'TBoss shares photos of herself heavily pregnant',
          slug: 'tboss-shares-photos-of-herself-heavily-pregnant-cf3e3adb',
          description: 'Na belle I carry, I nor kill person',
          body: 'In this report, the global Sunflower Oil Meal market is valued at USD XX million in 2019',
          imageUrl: 'http://image.png',
          isDraft: false,
          views: 0,
          read: 0,
          readRatio: 0,
          userId: 72,
          catId: 1,
        },
        {
          id: 167,
          title: 'Serena routs Sharapova',
          slug: 'serena-routs-sharapova-b3348661',
          description: 'US Open',
          body: 'In this report, the global Sunflower Oil Meal market is valued at USD XX million in 2019',
          imageUrl: 'http://image.png',
          isDraft: false,
          views: 0,
          read: 0,
          readRatio: 0,
          userId: 72,
          catId: 3,
        },
        {
          id: 100,
          title: 'Nicholas Pepe',
          slug: 'nicholas-pepe-491eb2e1',
          description: 'Reveals why he joined Arsenal',
          body: 'In this report, the global Sunflower Oil Meal market is valued at USD XX million in 2019',
          imageUrl: 'http://image.png',
          isDraft: false,
          views: 0,
          read: 0,
          readRatio: 0,
          userId: 72,
          catId: 2,
        },
        {
          id: 101,
          title: 'Join Andela',
          slug: 'join-andela-a9022aa4',
          description: 'Here is a chance to join Andela as a mid level and senior developer',
          body: 'In this report, the global Sunflower Oil Meal market is valued at USD XX million in 2019',
          imageUrl: 'http://image.png',
          isDraft: false,
          views: 0,
          read: 0,
          readRatio: 0,
          userId: 72,
          catId: 1,
        },
        {
          id: 102,
          title: 'Sunflower Oil Meal Market',
          slug: 'sunflower-oil-meal-market-00c9b66b',
          description: 'Key Development by 2025',
          body: 'In this report, the global Sunflower Oil Meal market is valued at USD XX million in 2019',
          imageUrl: 'http://image.png',
          isDraft: false,
          views: 0,
          read: 0,
          readRatio: 0,
          userId: 72,
          catId: 3,
        },
      ],
      totalArticles: 10,
      currentPage: '1',
      limit: '6',
      totalPages: 2,
    },
  ],
};

export const errorArticleResponse = {
  status: 404,
  message: 'Article not found',
};
